# Generated by Django 5.1.1 on 2024-09-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CbtBoard',
            fields=[
                ('PR_BOARD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(max_length=100)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_board',
            },
        ),
        migrations.CreateModel(
            name='CbtBookType',
            fields=[
                ('PR_BOOK_TYPE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(max_length=255)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_book_type',
            },
        ),
        migrations.CreateModel(
            name='CbtClasses',
            fields=[
                ('PR_CLASS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(max_length=100)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_classes',
            },
        ),
        migrations.CreateModel(
            name='CbtSeries',
            fields=[
                ('PR_SERIES_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(max_length=255)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PR_BOARD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookApp.cbtboard')),
            ],
            options={
                'db_table': 'cbt_series',
            },
        ),
        migrations.CreateModel(
            name='CbtBookData',
            fields=[
                ('PR_BOOK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_TITLE', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_SUB_TITLE', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_ISBN', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_IMPRINT', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_AUTHOR', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_EDITION', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_COMPANY', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_BOOK_CODE', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_COPYRIGHT', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_DATE_OF_RELEASE', models.DateField(blank=True, null=True)),
                ('PR_BINDING', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_LANGUAGE', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_PAGES', models.IntegerField(blank=True, null=True)),
                ('PR_TRIM_SIZE', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_WEIGHT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PR_LIST_PRICE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PR_DISCOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PR_BOOK_NUMBER', models.IntegerField(blank=True, null=True)),
                ('PR_CLASS_LEVEL', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_PRODUCT_DIVISION', models.CharField(blank=True, max_length=100, null=True)),
                ('PR_BROAD_SUBJECT', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_DETAILED_SUBJECT', models.CharField(blank=True, max_length=255, null=True)),
                ('PR_PRODUCT_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PR_BOARD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookApp.cbtboard')),
                ('PR_BOOK_TYPE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookApp.cbtbooktype')),
                ('PR_CLASS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookApp.cbtclasses')),
                ('PR_SERIES', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookApp.cbtseries')),
            ],
            options={
                'db_table': 'cbt_book_data',
            },
        ),
        migrations.CreateModel(
            name='CbtSeriesClass',
            fields=[
                ('PR_SERIES_CLASS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.cbtclasses')),
                ('PR_SERIES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.cbtseries')),
            ],
            options={
                'db_table': 'cbt_series_class',
                'unique_together': {('PR_CLASS', 'PR_SERIES')},
            },
        ),
        migrations.AddField(
            model_name='cbtseries',
            name='PR_CLASSES',
            field=models.ManyToManyField(related_name='series', through='bookApp.CbtSeriesClass', to='bookApp.cbtclasses'),
        ),
    ]
