# Generated by Django 5.1.1 on 2024-09-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbtSubject',
            fields=[
                ('PR_SUBJECT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_NAME', models.CharField(max_length=100)),
                ('PR_CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('PR_MODIFIED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbt_subject',
            },
        ),
        migrations.CreateModel(
            name='CbtClassSubject',
            fields=[
                ('PR_CLASS_SUBJECT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PR_CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.cbtclasses')),
                ('PR_SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.cbtsubject')),
            ],
            options={
                'db_table': 'cbt_class_subject',
            },
        ),
        migrations.AddField(
            model_name='cbtclasses',
            name='PR_SUBJECT',
            field=models.ManyToManyField(related_name='series', through='bookApp.CbtClassSubject', to='bookApp.cbtsubject'),
        ),
    ]
