# Generated by Django 5.1.1 on 2024-09-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_cbtsubject_cbtclasssubject_cbtclasses_pr_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtbookdata',
            name='PR_SUBJECT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookApp.cbtsubject'),
        ),
    ]
