# Generated by Django 5.1.1 on 2024-09-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0003_cbtbookdata_pr_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtclasses',
            name='PR_SUBJECT',
            field=models.ManyToManyField(related_name='pr_classes', through='bookApp.CbtClassSubject', to='bookApp.cbtsubject'),
        ),
        migrations.AlterField(
            model_name='cbtseries',
            name='PR_BOARD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_series', to='bookApp.cbtboard'),
        ),
        migrations.AlterField(
            model_name='cbtseries',
            name='PR_CLASSES',
            field=models.ManyToManyField(related_name='pr_series_classes', through='bookApp.CbtSeriesClass', to='bookApp.cbtclasses'),
        ),
    ]
