# Generated by Django 5.1.1 on 2024-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0004_alter_cbtclasses_pr_subject_alter_cbtseries_pr_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtboard',
            name='PR_STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cbtbookdata',
            name='PR_STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cbtbooktype',
            name='PR_STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cbtclasses',
            name='PR_STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cbtseries',
            name='PR_STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cbtsubject',
            name='PR_STATUS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
