# Generated by Django 5.1.1 on 2024-09-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0005_cbtboard_pr_status_cbtbookdata_pr_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtsubject',
            name='PR_CREATED_AT',
        ),
        migrations.AddField(
            model_name='cbtboard',
            name='PR_DESCRIPTION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtboard',
            name='PR_IMAGE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtbookdata',
            name='PR_DESCRIPTION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtbookdata',
            name='PR_IMAGE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtbooktype',
            name='PR_DESCRIPTION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtbooktype',
            name='PR_IMAGE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtclasses',
            name='PR_DESCRIPTION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtclasses',
            name='PR_IMAGE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtseries',
            name='PR_DESCRIPTION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtseries',
            name='PR_IMAGE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtsubject',
            name='PR_DESCRIPTION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cbtsubject',
            name='PR_IMAGE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtboard',
            name='PR_NAME',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_AUTHOR',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_BINDING',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_BOOK_CODE',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_BROAD_SUBJECT',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_CLASS_LEVEL',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_COMPANY',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_COPYRIGHT',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_DETAILED_SUBJECT',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_EDITION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_IMPRINT',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_ISBN',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_LANGUAGE',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_PRODUCT_DIVISION',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_SUB_TITLE',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_TITLE',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbookdata',
            name='PR_TRIM_SIZE',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cbtbooktype',
            name='PR_NAME',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cbtclasses',
            name='PR_NAME',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cbtseries',
            name='PR_NAME',
            field=models.CharField(default='', max_length=255),
        ),
    ]
