# Generated by Django 5.1.1 on 2024-09-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0006_remove_cbtsubject_pr_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtclasssubject',
            name='PR_SUBJECT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PR_SUBJECT', to='bookApp.cbtsubject'),
        ),
    ]
